version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    image: mollee/gitrecruit-frontend:dev
    stdin_open: true
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    image: mollee/gitrecruit-backend:dev
    environment:
      DB_USER: gitrecruit
      DB_NAME: gitrecruit
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./backend:/usr/share/app

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: gitrecruit
      PORTGRES_DB: gitrecruit
      POSTGRES_PASSWORD: password
