version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    image: mollee/gitrecruit-frontend:dev
    stdin_open: "true"
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/share/app/src

  backend:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    image: mollee/gitrecruit-backend:dev
    ports:
      - 8080:8080
    volumes:
      - ./backend/src:/usr/share/app/src
